# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaEntrada.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(428, 599)
        self.titulo = QtWidgets.QLabel(Dialog)
        self.titulo.setGeometry(QtCore.QRect(-20, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.subtitulo = QtWidgets.QLabel(Dialog)
        self.subtitulo.setGeometry(QtCore.QRect(20, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtitulo.setFont(font)
        self.subtitulo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subtitulo.setObjectName("subtitulo")
        self.subtitulo_2 = QtWidgets.QLabel(Dialog)
        self.subtitulo_2.setGeometry(QtCore.QRect(20, 260, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtitulo_2.setFont(font)
        self.subtitulo_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subtitulo_2.setObjectName("subtitulo_2")
        self.comboBox_senial = QtWidgets.QComboBox(Dialog)
        self.comboBox_senial.setGeometry(QtCore.QRect(20, 90, 161, 22))
        self.comboBox_senial.setObjectName("comboBox_senial")
        self.comboBox_senial.addItem("")
        self.comboBox_senial.addItem("")
        self.comboBox_senial.addItem("")
        self.comboBox_senial.addItem("")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 310, 211, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_amplitud_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_amplitud_2.setObjectName("label_amplitud_2")
        self.gridLayout_2.addWidget(self.label_amplitud_2, 0, 0, 1, 1)
        self.lineEdit_tao = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_tao.setObjectName("lineEdit_tao")
        self.gridLayout_2.addWidget(self.lineEdit_tao, 0, 1, 1, 1)
        self.label_frecuencia_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_frecuencia_2.setObjectName("label_frecuencia_2")
        self.gridLayout_2.addWidget(self.label_frecuencia_2, 1, 0, 1, 1)
        self.lineEdit_t = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.gridLayout_2.addWidget(self.lineEdit_t, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 150, 191, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_amplitud = QtWidgets.QLabel(self.layoutWidget1)
        self.label_amplitud.setObjectName("label_amplitud")
        self.gridLayout.addWidget(self.label_amplitud, 0, 0, 1, 1)
        self.label_frecuencia = QtWidgets.QLabel(self.layoutWidget1)
        self.label_frecuencia.setObjectName("label_frecuencia")
        self.gridLayout.addWidget(self.label_frecuencia, 1, 0, 1, 1)
        self.lineEdit_frecuencia = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_frecuencia.setObjectName("lineEdit_frecuencia")
        self.gridLayout.addWidget(self.lineEdit_frecuencia, 1, 1, 1, 1)
        self.lineEdit_amplitud = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_amplitud.setObjectName("lineEdit_amplitud")
        self.gridLayout.addWidget(self.lineEdit_amplitud, 0, 1, 1, 1)
        self.lineEdit_periodo = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_periodo.setObjectName("lineEdit_periodo")
        self.gridLayout.addWidget(self.lineEdit_periodo, 2, 1, 1, 1)
        self.label_frecuencia_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_frecuencia_3.setObjectName("label_frecuencia_3")
        self.gridLayout.addWidget(self.label_frecuencia_3, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 550, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.subtitulo_3 = QtWidgets.QLabel(Dialog)
        self.subtitulo_3.setGeometry(QtCore.QRect(20, 400, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtitulo_3.setFont(font)
        self.subtitulo_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subtitulo_3.setObjectName("subtitulo_3")
        self.comboBox_tipo_muestreo = QtWidgets.QComboBox(Dialog)
        self.comboBox_tipo_muestreo.setGeometry(QtCore.QRect(20, 440, 161, 22))
        self.comboBox_tipo_muestreo.setObjectName("comboBox_tipo_muestreo")
        self.comboBox_tipo_muestreo.addItem("")
        self.comboBox_tipo_muestreo.addItem("")
        self.comboBox_tipo_muestreo.addItem("")
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(230, 150, 181, 91))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_amplitud_moduladora = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_amplitud_moduladora.setObjectName("lineEdit_amplitud_moduladora")
        self.gridLayout_5.addWidget(self.lineEdit_amplitud_moduladora, 0, 1, 1, 1)
        self.label_fin_rango_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_fin_rango_2.setObjectName("label_fin_rango_2")
        self.gridLayout_5.addWidget(self.label_fin_rango_2, 1, 0, 1, 1)
        self.lineEdit_frecuencia_moduladora = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_frecuencia_moduladora.setObjectName("lineEdit_frecuencia_moduladora")
        self.gridLayout_5.addWidget(self.lineEdit_frecuencia_moduladora, 1, 1, 1, 1)
        self.label_inicio_rango_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_inicio_rango_2.setObjectName("label_inicio_rango_2")
        self.gridLayout_5.addWidget(self.label_inicio_rango_2, 0, 0, 1, 1)
        self.lineEdit_coeficiente = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_coeficiente.setObjectName("lineEdit_coeficiente")
        self.gridLayout_5.addWidget(self.lineEdit_coeficiente, 2, 1, 1, 1)
        self.label_fin_rango_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_fin_rango_3.setObjectName("label_fin_rango_3")
        self.gridLayout_5.addWidget(self.label_fin_rango_3, 2, 0, 1, 1)
        self.label_moduladora = QtWidgets.QLabel(Dialog)
        self.label_moduladora.setGeometry(QtCore.QRect(234, 120, 91, 20))
        self.label_moduladora.setText("")
        self.label_moduladora.setObjectName("label_moduladora")
        self.label_portadora = QtWidgets.QLabel(Dialog)
        self.label_portadora.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_portadora.setText("")
        self.label_portadora.setObjectName("label_portadora")
        self.subtitulo_4 = QtWidgets.QLabel(Dialog)
        self.subtitulo_4.setGeometry(QtCore.QRect(20, 470, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtitulo_4.setFont(font)
        self.subtitulo_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subtitulo_4.setObjectName("subtitulo_4")
        self.lineEdit_nombre = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(20, 510, 161, 22))
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Señal de Entrada"))
        self.titulo.setText(_translate("Dialog", "SEÑAL DE ENTRADA"))
        self.subtitulo.setText(_translate("Dialog", "Introduzca la señal deseada"))
        self.subtitulo_2.setText(_translate("Dialog", "Introduzca las caracteristicas del muestreo deseado"))
        self.comboBox_senial.setItemText(0, _translate("Dialog", "Senoidal"))
        self.comboBox_senial.setItemText(1, _translate("Dialog", "Cuadratica"))
        self.comboBox_senial.setItemText(2, _translate("Dialog", "3/2Senoidal"))
        self.comboBox_senial.setItemText(3, _translate("Dialog", "AM"))
        self.label_amplitud_2.setText(_translate("Dialog", "Tiempo Tao (s)"))
        self.label_frecuencia_2.setText(_translate("Dialog", "Tiempo T (s)"))
        self.label_amplitud.setText(_translate("Dialog", "Amplitud (V)"))
        self.label_frecuencia.setText(_translate("Dialog", "Frecuencia (Hz)"))
        self.label_frecuencia_3.setText(_translate("Dialog", "Cant de períodos"))
        self.subtitulo_3.setText(_translate("Dialog", "Inserte el tipo de muestreo"))
        self.comboBox_tipo_muestreo.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_tipo_muestreo.setItemText(1, _translate("Dialog", "Natural"))
        self.comboBox_tipo_muestreo.setItemText(2, _translate("Dialog", "Instantaneo"))
        self.label_fin_rango_2.setText(_translate("Dialog", "Frecuencia (Hz)"))
        self.label_inicio_rango_2.setText(_translate("Dialog", "Amplitud (V)"))
        self.label_fin_rango_3.setText(_translate("Dialog", "Coeficiente"))
        self.subtitulo_4.setText(_translate("Dialog", "Introduzca Nombre de la señal (label en grafico)"))

